### ISSUE TITLE
Add custom variable to turn off symbol occurrence count in highlight-symbol-mode

### ISSUE THREAD

**Issue by bsuh** [nschum/highlight-symbol.el#30]
When using flycheck, some symbols get underlined to indicate an error or warning. When you put the cursor on the symbol, it will show the error or warning message in the message buffer. Using `highlight-symbol-mode`, you only have `highlight-symbol-idle-delay` (default 1.5 seconds) to read the error or warning message, before it is overwritten by the symbol occurrence count.

**Comment by nschum** [comment]
Should be fixed by #31. Thanks @tsdh
