### ISSUE TITLE
Symbols starting or ending with colon not highlighted (ruby-mode)

### ISSUE THREAD

**Issue by patrickmclaren** [nschum/highlight-symbol.el#39]
Highlighting `foo` in the following example in a ruby-mode buffer only highlights the first and last occurrence of `foo`.

``` ruby
foo = :bar
bar = :foo

puts foo
```

One could argue this is working as intended, since `foo` is not `:foo`. However I was expecting similar behavior to other modes, i.e. highlight `foo` for `var foo = { foo: "bar" };` in javascript-mode.

Using latest version from marmalade (20160102.1209) with Emacs 24.5.1.

**Comment by nschum** [comment]
`ruby-mode` gives the colon "symbol" syntax, other modes define it as "punctuation". (See documentation for `modify-syntax-entry`.) So as far as Emacs is concerned, `foo` is indeed not `:foo`.

Unfortunately, I don't see a reasonable around this.

**Comment by dgutov** [comment]
> ruby-mode gives the colon "symbol" syntax

This will change in Emacs 25 (EDIT: now done).
